Fix osx build and git user conflict
tiiuae/px4-firmware pull request #541
Opened 2023-10-31 13:42 UTC by gpoulios

### Solved Problem
When building under OSX the typical user group (staff) has a GID of 20 conflicting with some Ubuntu system group of the container. Additionally if the git users between the host and container don't match (repo cloned on host, used in container), git aborts with a fatal error. 

### Solution
- Add '-o' option to groupadd to allow for multiple group names pointing to the same GID
- Mark the sources directory as a 'safe.directory' for git inside the container

### Alternatives
- '-o' option: perhaps we could use the existing group name but I suppose that would add too much bloat in the dockerfile
- git safe dir: perhaps we could COPY the host's user git config over to the container though I'm not sure of how portable that can be.

### Test coverage
- Tested only under OSX.

2023-10-31 17:44 UTC, jlaitine approved these changes
LGTM

2023-10-31 18:03 UTC, jlaitine requested changes
Actually, could you still check why the CI is failing for this? Can be of course unrelated, but previous PR:s passed today...

2023-11-01 12:47 UTC, jlaitine approved these changes
What ever was the problem with CI, it seems to be fixed by itself

2023-11-01 16:58 UTC, gpoulios commented
Magic. It seemed random in the first place.

Merging this.

2023-11-01 16:58 UTC, merged