DP-8235 bootloader_v2 compatible px_uploader.sh to px4 image container
tiiuae/px4-firmware pull request #620
Opened 2024-01-29 11:18 UTC by TimoSairiala

The script is copied from
https://github.com/tiiuae/saluki_bootloader_v2/blob/master/tools/px_uploader.py
This is a short term fix. In the long we better have one script in one place

2024-01-30 07:44 UTC, jlaitine commented
We can't just replace the script; in the very near future we will need to support some COTS devices such as the new ones based on NXP chipsets (and still need to be able to flash fmu-v5x). Just replacing the script breaks the flashing of those.

2024-01-30 07:49 UTC, jlaitine requested changes
If the uploader script for salukis are absolutely needed in here, there is some other solution needed than replacing the existing one.

2024-01-30 08:48 UTC, TimoSairiala commented
ok, we agreed to include this updated script to px4 image container and leave repo tree as it is. I'll update the commit

2024-02-01 08:25 UTC, jnippula approved these changes

2024-02-01 10:09 UTC, merged